server:
  port: 8098
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      db1:
        username: root
        password: abc123
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: root
        password: abc123
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/osd_gas?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
        initialSize: 5
        minIdle: 5
        maxActive: 20
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0